### ISSUE TITLE
[help-wanted]Step-by-step solution to extract semi-structured data

### ISSUE THREAD

**Issue by gomathykailas** [spring-cloud/spring-cloud-stream-modules#206] opened 2016-03-02 16:10 UTC
Hi,
Is there a way to **extract semi-structured data** from a file in spring-cloud-dataflow ?

Consider an example below ( a line with values delimited by pipe )

_**919266728292|20.0|COREBALANCE|1&**Core**&0.0040&1&+&2&0&102&LOCAL_MINS_BALANCE&0.0000&2&+&2&0&342|70.0**_

Eg: If I need to extract the value "**_Core_**" from line above , 
then we need to do extraction as

Extract the line using pipe symbol ( | ) ,take 4th one to get value as _1&Core&0.0040&1&+&2&0&102&LOCAL_MINS_BALANCE&0.0000&2&+&2&0&342_
Split above result obtained with + , to get value as _1&Core&0.0040&1&_
Split above result obtained with &, to get value as _**Core**_

If we can do any extractions , **please provide step-by-step solution of how to do extraction in this particular example given above**

**Comment by sabbyanandan** [comment] 2016-03-02 16:20
This is a duplicate of: spring-cloud/spring-cloud-dataflow#427; closing it.

What you're describing here is a use-case and we expect users to develop the solution on their own either using the OOTB or as custom applications supported by Spring Cloud Data Flow/Spring Cloud Stream projects. If you find any bugs with the OOTB applications or looking for an improvement, please open a issue.

**Closed by sabbyanandan** 2016-03-02 16:20 UTC
